//What food would pair well with this track
export const artistPresets = [
  { "artistname": "Izabel ~ WORDS BY: Emile Frankel ~ VISUALS BY: Mohamed Chamas",
    "emoji01": require("./emojis/desert.png").default,
    "emoji01width": "1.6vw",
    "emoji01alt": "desert emoji",
    "emoji02": require("./emojis/blossoming-flower.png").default,
    "emoji02width": "1.6vw",    
    "emoji02alt": "blooming flower emoji",
    "emoji03": require("./emojis/mushroom.png").default,
    "emoji03width": "1.6vw",
    "emoji03alt": "mushroom emoji" 
  },
  { "artistname": "Hani Hanbali ~ WORDS BY: Emile Frankel ~ VISUALS BY: Mohamed Chamas",
    "emoji01": require("./emojis/alien.png").default,
    "emoji01width": "1.6vw",
    "emoji01alt": "alien face emoji",
    "emoji02": require("./emojis/woozy.png").default,
    "emoji02width": "1.6vw",
    "emoji02alt": "woozy emoji",
    "emoji03": require("./emojis/teddy-bear.png").default,
    "emoji03width": "1.6vw",    
    "emoji03alt": "teddy bear emoji"   
  },
  { "artistname": "Hannah Wu ~ WORDS BY: Panda Wong ~ VISUALS BY: Mohamed Chamas",
    "emoji01": require("./emojis/butterfly.png").default,
    "emoji01width": "1.6vw",
    "emoji01alt": "butterfly emoji",
    "emoji02": require("./emojis/leaf-in-wind.png").default,
    "emoji02width": "1.6vw",
    "emoji02alt": "leaf in wind emoji",
    "emoji03": require("./emojis/spiral-shell.png").default,
    "emoji03width": "1.6vw",    
    "emoji03alt": "spiral shell emoji" 
  },
]